name: Deploy AWS CRC Front-end

run-name: ${{ github.actor }} has pushed changes to the Main Branch

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:

  deploy_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Install modules ğŸ§‘â€ğŸ­
        run: 
          npm ci
      
      - name: Build application ğŸ› ï¸
        run: 
          npx astro build

      - name: Deploy to S3 ğŸš€
        run: 
          aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      
      - name: Create CloudFront invalidation â˜ï¸
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
  
  cypress_test_job:
    runs-on: ubuntu-latest
    needs: deploy_job

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout â˜‘ï¸
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Cypress and dependencies ğŸ¤™
        run: |
          npm install cypress
          pnpm install --no-frozen-lockfile

      - name: Cypress Tests ğŸ“œ
        uses: cypress-io/github-action@v6
        with:
          build: npx astro build
          start: npx astro preview
          browser: chrome
