name: Deploy AWS CRC Front-end

run-name: ${{ github.actor }} has pushed changes to the Main Branch

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Step 2: Setup AWS credentials and secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      # Step 3: Install project dependencies
      - name: Install modules
        run: npm ci

      # Step 4: Build the project
      - name: Build application
        run: npx astro build

      # Step 5: Deploy your website to S3
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      
      # Step 6: Invalidate CF cache
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
