name: Deploy AWS CRC Front-end

run-name: ${{ github.actor }} has pushed changes to the Main Branch

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout â˜‘ï¸
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Install dependencies ğŸ§‘â€ğŸ­
        run: |
          cd ./frontend &&
          npm install
      
      - name: Build application ğŸ› ï¸
        run: |
          cd ./frontend &&
          npx astro build

      - name: Deploy to S3 ğŸš€
        run: 
          aws s3 sync --delete ./frontend/dist/ s3://${{ secrets.BUCKET_ID }}
      
      - name: Create CloudFront invalidation â˜ï¸
        run: |
          cd ./frontend &&
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
  
  cypress_test_website:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout â˜‘ï¸
        uses: actions/checkout@v4

      - name: Install pnpm â˜‘ï¸
        run: | 
          cd ./frontend &&
          npm install -g pnpm@latest

      - name: Install Cypress and dependencies ğŸ¤™
        run: |
          cd ./frontend &&
          npm install cypress
          pnpm install --no-frozen-lockfile

      - name: Cypress Tests ğŸ“œ
        uses: cypress-io/github-action@v6
        with:
          working-directory: './frontend'
          build: npx astro build
          start: npx astro preview
          command-prefix: 'percy exec -- '
          command: npx cypress run
          publish-summary: true
          summary-title: 'website-portfolio-test'

